# STUDENT RESULTS DATABASE MANAGEMENT

In [1]:
import numpy as np

## Creating a dataset

In [2]:
dataset = np.random.randint(0,101, size=(100,5))
print("Students marks dataset:",dataset)

Students marks dataset: [[ 65  86  29  81  82]
 [ 46  94  42  20  49]
 [ 14  92   4  36  88]
 [ 20  42  47  87  12]
 [ 17  21  12   4  73]
 [ 95  66  24  87  66]
 [ 94  41  77  98  62]
 [ 82  33  86  74  56]
 [  3  90  88   2  25]
 [ 92  99  83  65   6]
 [ 74  80  64  73  98]
 [  3  71  94  81  90]
 [ 61  26  58  51  90]
 [ 68  88  83  58  78]
 [  3  11  30  34  31]
 [ 53  50   2  90  88]
 [ 11   3  16  64  14]
 [ 19  93  21  36  56]
 [ 35  84  62  67  79]
 [ 53  55  81  76  45]
 [ 67  55  93  99  34]
 [ 56   7   3  27  13]
 [ 23  76  54  23  46]
 [ 12  85  72  52  98]
 [ 60  98  14  23  18]
 [ 69  35   2  29   3]
 [ 27  92   4   4  49]
 [ 47  72  70  89  24]
 [ 90  14  19  42  98]
 [ 19  51  51  50   1]
 [ 82  55  47  76  83]
 [ 48  27  25  15  47]
 [ 80  95  69  62  18]
 [ 17  51  47  61   8]
 [ 39  62 100  12  27]
 [ 20  48  40  93  27]
 [ 73  73  30  79  58]
 [ 64  47  61  35 100]
 [ 93  54  67  69  33]
 [  2  67  71  46  29]
 [ 81  13   7   1  48]
 [ 45  53  15  73  77]
 [ 50  41 

## Adding Labels

In [3]:
student_ids = np.arange(1, 101)
subject_names = ['Math', 'Physics', 'Chemistry', 'Biology', 'English']

## Sum of total marks

In [4]:
total_marks = np.sum(dataset, axis=1)
print("Sum of each student's marks:", total_marks)

Sum of each student's marks: [343 251 234 208 127 338 372 331 208 345 389 339 286 375 109 283 108 225
 327 310 348 106 222 319 213 138 176 302 263 172 343 162 324 184 240 228
 313 307 316 215 150 263 242 173 182 287 238 238 251 354 170 336 271 308
 206 304 288 116 302 321 194 266 259 276 266 218 250 338 298  86 280 217
 243 100 262 130 286 202 251 269 179 266 359 182 262 366 316 285 261 402
 254 286 301 290 205 193 185 353 300 291]


## Top 5 Students

In [5]:
top_5_indices = np.argsort(total_marks)[::-1][:5]
top_5_scores = total_marks[top_5_indices]
print("Top 5 Students:",top_5_scores)


Top 5 Students: [402 389 375 372 366]


## Subject Wise Statistics


In [6]:
avg_marks_per_subject = np.mean(dataset,axis=0)
print("Average marks per subject:",avg_marks_per_subject)

Average marks per subject: [47.6  59.35 53.64 48.44 47.23]


In [7]:
min_marks_per_subject = np.min(dataset, axis=0)
print("Minimum marks per subject:", min_marks_per_subject)

Minimum marks per subject: [0 0 0 1 0]


In [8]:
max_marks_per_subject = np.max(dataset, axis=0)
print("Maximum marks per subject:", max_marks_per_subject)

Maximum marks per subject: [ 98 100 100  99 100]


In [9]:
topper_per_subject = np.argmax(dataset, axis=0)
print("Topper per subject:", topper_per_subject)

Topper per subject: [85 47 34 20 37]


## Output Insights

In [10]:
print("Top 5 Students (by total marks):")
for i in range(5):
    print(f"Student {top_5_indices[i]+1}: {top_5_scores[i]} marks")

print("Subject-wise Averages:", avg_marks_per_subject)
print("Subject-wise Maximums:", max_marks_per_subject)
print("Subject-wise Minimums:", min_marks_per_subject)

print("\nTopper in Each Subject:")
for i, idx in enumerate(topper_per_subject):
    print(f"{subject_names[i]}: Student {idx+1} with {dataset[idx][i]} marks")


Top 5 Students (by total marks):
Student 90: 402 marks
Student 11: 389 marks
Student 14: 375 marks
Student 7: 372 marks
Student 86: 366 marks
Subject-wise Averages: [47.6  59.35 53.64 48.44 47.23]
Subject-wise Maximums: [ 98 100 100  99 100]
Subject-wise Minimums: [0 0 0 1 0]

Topper in Each Subject:
Math: Student 86 with 98 marks
Physics: Student 48 with 100 marks
Chemistry: Student 35 with 100 marks
Biology: Student 21 with 99 marks
English: Student 38 with 100 marks
